[package]
name = "easyhttpmock-vetis-smol"
version = "0.1.1"
edition = "2021"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/easyhttpmock"
homepage = "https://github.com/ararog/easyhttpmock"
description = "EasyHttpMock adapter for Vetis HTTP server using tokio runtime."
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["http", "mock", "testing"]
publish = true
rust-version = "1.75.0"

[package.metadata.docs.rs]
all-features = true

[features]
default = [
  "http2",
  #"http3"
]

xml = ["easyhttpmock/xml"]
json = ["easyhttpmock/json"]
http2 = ["vetis-smol/http2"]
http3 = ["vetis-smol/http3"]

rust-tls = ["vetis-smol/rust-tls"]

[dependencies]
#caramelo = { path = "../caramelo/caramelo" }
caramelo = { version = "0.1.5" }
easyhttpmock = { git = "https://github.com/easyhttpmock/easyhttpmock.git" }
#easyhttpmock = { path = "../easyhttpmock/easyhttpmock" }
#easyhttpmock = { version = "0.1.5-beta.2" }
http = "1.5.0"
http-body-util = "0.1.5"
macro_rules_attribute = "0.2.2"
rand = { version = "0.10.2", default-features = false }
smol = { version = "2.0.2", default-features = false }
smol-macros = { version = "0.1.1", default-features = false }
# vetis-smol = { path = "../vetis-smol", features = [
#   "http2",
#   #"http3",
#   "rust-tls",
# ], default-features = false }
# vetis-smol = { version = "0.1.2-beta.4", features = [
#   "http2",
#   #"http3",
#   "rust-tls",
# ], default-features = false }

[dev-dependencies]
deboa = { path = "../deboa/deboa" }
#deboa = { version = "0.1.5-beta.2" }
deboa-smol = { path = "../deboa-smol/deboa-smol", default-features = false, features = [
  "http2",
  #"http3",
  "rust-tls",
  "default-rustls-provider",
  "default-rustls-verifier",
] }
# deboa-smol = { version = "0.1.4-beta.3", default-features = false, features = [
#   "http2",
#   #"http3",
#   "rust-tls",
#   "default-rustls-provider",
#   "default-rustls-verifier",
# ] }
smol = { version = "2.0.2", default-features = false }
smol-macros = { version = "0.1.1", default-features = false }
